### ISSUE TITLE
Retrieve Soda Core check outputs as JSON/Dict

### ISSUE THREAD

**Issue by fakhavan** [sodadata/prefect-soda-core#16]
Hi there,

I'm in the process of migrating from Prefect 1 to Prefect 2 and have been exploring the use of the Perfect 2 with your `prefect-soda-core` package. I'm impressed with the block abstraction in Prefect 2, and I noticed that your package has been updated to support this abstraction for running Soda checks.

However, I noticed that your package is using the shell command to run the Soda code, which means that the output of the jobs is only available in the stdout format. As I use this library independent of Soda Cloud, I prefer having a dictionary/JSON output that I can easily manipulate and use.

I think this could be achieved by changing your package to use and execute soda-core methods directly so that the task can return dictionary objects containing Soda check results. 
Alternatively, an option to store the JSON-based output in a specified location using the [`--scan-results-file` param from the soda-core library](https://docs.soda.io/soda-core/scan-core.html#add-scan-options) could be added.

I'd be happy to contribute to this change if it makes sense to you. 
Thanks!

**Comment by AlessandroLollo** [comment]
Hey @fakhavan 👋 
When I started working on the `prefect-soda-core` collection implementation, I started by using Soda Core methods.
However, after a bit of testing, I discovered there were serialization issues within a Prefect flow that would have required a big refactor of Soda Core.

Together with @vijaykiran, we decided to refactor the implementation to make use of the Soda Core CLI to avoid having those serialization issues.

I'd be more than happy if you will to contribute a PR to implement the use case you described.
And I think that many people would benefit from such feature!

Best,
Ale

**Comment by fakhavan** [comment]
Hi @AlessandroLollo 

Thanks for your explaining the context on why the shell task was being used to make this task. I raised [a PR](https://github.com/sodadata/prefect-soda-core/pull/17) proposing changes to accept the `scan_results_file` param. Looking forwards to your feedback. 

Cheers

**Comment by AlessandroLollo** [comment]
Hey @fakhavan 👋 

I've just merged [this PR](https://github.com/sodadata/prefect-soda-core/pull/21) (starting from your previous one).
Let me know if I can close this issue!

**Comment by AlessandroLollo** [comment]
Sovled by https://github.com/sodadata/prefect-soda-core/pull/21
