### ISSUE TITLE
Issues with the example code

### ISSUE THREAD

**Issue by digitalghost-dev** [sodadata/prefect-soda-core#31]
With the example code on the docs page, there are some issues I have ran into:
1. Missing a comma on line 26 after, `verbose=True`
2. Running the code at first gives an error: `NameError: name 'get_run_context' is not defined`

**Comment by AlessandroLollo** [comment]
Hey @digitalghost-dev 👋 
The issue in the README example should be solved in `v0.1.8`.
Give it a try!

And thanks @zzstoatzz for the hints!
